### ISSUE TITLE
Bubble weapon makes dead goblins temporarily appear.

### ISSUE THREAD

**Issue by GrzegorzGrzelczyk** [symbol24/JernJam2024#1]
When the bubble weapon touches a goblin a lot of goblin sprites appear on the screen. They disappear after the attack animation is done.

I noticed that all of them were green even when attacking brown goblins until I killed a brown goblin. After that even when attacking a green goblin a brown one appeared as well. That's why I assume it shows sprites of already killed ones.

![3](https://github.com/user-attachments/assets/94c2da80-0b44-4df7-a18b-3ef5f16de39e)
![4](https://github.com/user-attachments/assets/96a4af71-bc4e-4597-8b92-6019f84edddd)

**Comment by symbol24** [comment]
fixed
